# Generated by Django 3.0 on 2021-11-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('poto', models.ImageField(default='', upload_to='galeri')),
            ],
        ),
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='List_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=200)),
                ('list', models.ManyToManyField(to='_app.List')),
            ],
        ),
        migrations.CreateModel(
            name='Paket_transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tujuan', models.CharField(max_length=200)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan_paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('nomor_hp', models.CharField(max_length=200)),
                ('jumlah_orang', models.CharField(max_length=100)),
                ('tanggal_jemput', models.DateField()),
                ('paket', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paket_tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=200)),
                ('poto', models.ImageField(default='', upload_to='paket_tour')),
                ('durasi', models.CharField(max_length=200)),
                ('harga', models.CharField(max_length=200)),
                ('list_paket', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='_app.List_tour')),
            ],
        ),
    ]
