# Generated by Django 3.0 on 2021-11-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0002_auto_20211126_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket_tour',
            name='list_paket',
            field=models.ManyToManyField(related_name='list_pakets', to='_app.List_tour'),
        ),
    ]
