# Generated by Django 3.0 on 2021-11-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0003_auto_20211126_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_tour',
            name='list',
            field=models.ManyToManyField(related_name='lists', to='_app.List'),
        ),
    ]
