# Generated by Django 3.0 on 2021-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0004_auto_20211126_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_harga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.CharField(max_length=200)),
                ('jumlah', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='paket_tour',
            name='detail_harga',
            field=models.ManyToManyField(to='_app.Detail_harga'),
        ),
    ]
